# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matol699/Kurser/TDDC76/Projekt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matol699/Kurser/TDDC76/Projekt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matol699/Kurser/TDDC76/Projekt/CMakeFiles /home/matol699/Kurser/TDDC76/Projekt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matol699/Kurser/TDDC76/Projekt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/matol699/Kurser/TDDC76/Projekt/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

src/engine/states/GameState.o: src/engine/states/GameState.cc.o

.PHONY : src/engine/states/GameState.o

# target to build an object file
src/engine/states/GameState.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/GameState.cc.o
.PHONY : src/engine/states/GameState.cc.o

src/engine/states/GameState.i: src/engine/states/GameState.cc.i

.PHONY : src/engine/states/GameState.i

# target to preprocess a source file
src/engine/states/GameState.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/GameState.cc.i
.PHONY : src/engine/states/GameState.cc.i

src/engine/states/GameState.s: src/engine/states/GameState.cc.s

.PHONY : src/engine/states/GameState.s

# target to generate assembly for a file
src/engine/states/GameState.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/GameState.cc.s
.PHONY : src/engine/states/GameState.cc.s

src/engine/states/MenuState.o: src/engine/states/MenuState.cc.o

.PHONY : src/engine/states/MenuState.o

# target to build an object file
src/engine/states/MenuState.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/MenuState.cc.o
.PHONY : src/engine/states/MenuState.cc.o

src/engine/states/MenuState.i: src/engine/states/MenuState.cc.i

.PHONY : src/engine/states/MenuState.i

# target to preprocess a source file
src/engine/states/MenuState.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/MenuState.cc.i
.PHONY : src/engine/states/MenuState.cc.i

src/engine/states/MenuState.s: src/engine/states/MenuState.cc.s

.PHONY : src/engine/states/MenuState.s

# target to generate assembly for a file
src/engine/states/MenuState.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/states/MenuState.cc.s
.PHONY : src/engine/states/MenuState.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/objects/Collidable.o: src/objects/Collidable.cc.o

.PHONY : src/objects/Collidable.o

# target to build an object file
src/objects/Collidable.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Collidable.cc.o
.PHONY : src/objects/Collidable.cc.o

src/objects/Collidable.i: src/objects/Collidable.cc.i

.PHONY : src/objects/Collidable.i

# target to preprocess a source file
src/objects/Collidable.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Collidable.cc.i
.PHONY : src/objects/Collidable.cc.i

src/objects/Collidable.s: src/objects/Collidable.cc.s

.PHONY : src/objects/Collidable.s

# target to generate assembly for a file
src/objects/Collidable.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Collidable.cc.s
.PHONY : src/objects/Collidable.cc.s

src/objects/Player.o: src/objects/Player.cc.o

.PHONY : src/objects/Player.o

# target to build an object file
src/objects/Player.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Player.cc.o
.PHONY : src/objects/Player.cc.o

src/objects/Player.i: src/objects/Player.cc.i

.PHONY : src/objects/Player.i

# target to preprocess a source file
src/objects/Player.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Player.cc.i
.PHONY : src/objects/Player.cc.i

src/objects/Player.s: src/objects/Player.cc.s

.PHONY : src/objects/Player.s

# target to generate assembly for a file
src/objects/Player.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/objects/Player.cc.s
.PHONY : src/objects/Player.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... src/engine/states/GameState.o"
	@echo "... src/engine/states/GameState.i"
	@echo "... src/engine/states/GameState.s"
	@echo "... src/engine/states/MenuState.o"
	@echo "... src/engine/states/MenuState.i"
	@echo "... src/engine/states/MenuState.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects/Collidable.o"
	@echo "... src/objects/Collidable.i"
	@echo "... src/objects/Collidable.s"
	@echo "... src/objects/Player.o"
	@echo "... src/objects/Player.i"
	@echo "... src/objects/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/matol699/Kurser/TDDC76/Projekt/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

